### ISSUE TITLE
Incorrect Coffee Table Texture

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishMoreFurnitureMod#4]
`Minecraft v1.16.5`
`Forge v36.1.24`
`More cfm v1.1.2`

Coffee Tables all use the stripped oak log texture for the legs of the table.

![2021-06-03_21 50 30](https://user-images.githubusercontent.com/12000593/120738617-c816e380-c4b5-11eb-86a2-0306e6ff9da1.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishMoreFurnitureMod/commit/d4844da7635579673c50a00dd5aa8db39d3d3ffc and available in v1.2.0

**Comment by WenXin20** [comment]
Thank you!
